//Close collapsible menu upon detecting outside click

//Facebook popup window
function openWindow(url,height,width) {
  window.open(url,"_blank","height="+height+",width="+width);
  return false;
}
function share(type) {
  var url = escape(window.location.href);
  var site = 'HoustonChronicle.com';
  var title = escape(document.title);
  if ( type == 'facebook' ) {
    openWindow('http://www.facebook.com/sharer.php?u=' + url,400,750);
  }
  return false;
}
//Show about page and return to restaurants section
$('.showabout').click(function() {
    if ($("#about") .is(':visible')) {
		$("#about").hide();
		$("#restaurantfilter").show();
		$('.showabout') .removeClass("selected");
    } else {
		$("#about").show();
		$("#restaurantfilter").hide();
		$("#numbers").hide();
		$('.revertnew').hide();
		$('.new').show();
		$('.showabout') .addClass("selected");
		$('.bythenumbers') .removeClass("selected");
		$('.formclone') .hide();
		$('.clone') .hide();
	}
});
//Show numbers page and return to restaurants section
$('.bythenumbers').click(function() {
    if ($("#numbers") .is(':visible')) {
		$("#numbers").hide();
		$("#restaurantfilter").show();
		$('.bythenumbers') .removeClass("selected");
    } else {
		$("#numbers").show();
		$("#restaurantfilter").hide();
		$("#about").hide();
		$('.revertnew').hide();
		$('.new').show();
		$('.bythenumbers') .addClass("selected");
		$('.showabout') .removeClass("selected");
		$('.formclone') .hide();
		$('.clone') .hide();
	}
});
//Goes from about page to selected values already filtered
$(".clear") .click(function() {
	$("#about").hide();
	$("#numbers").hide();
	$('.revertnew').hide();
	$('.new').show();
	$("#restaurantfilter").show();
	$('.showabout') .removeClass("selected");
	$('.bythenumbers') .removeClass("selected");
});
$(".cuisines") .change(function() {
	var val = $(this).val();
	 if(val === $(this).val()) {
        $("#about").hide();
		$("#numbers").hide();
		$("#restaurantfilter").show();
		$('.showabout') .removeClass("selected");
		$('.bythenumbers') .removeClass("selected");
    }
});
$(".neighborhood") .change(function() {
	var val = $(this).val();
	 if(val === $(this).val()) {
        $("#about").hide();
		$("#numbers").hide();
		$("#restaurantfilter").show();
		$('.showabout') .removeClass("selected");
		$('.bythenumbers') .removeClass("selected");
    }
});
$(".price") .change(function() {
	var val = $(this).val();
	 if(val === $(this).val()) {
        $("#about").hide();
		$("#numbers").hide();
		$("#restaurantfilter").show();
		$('.showabout') .removeClass("selected");
		$('.bythenumbers') .removeClass("selected");
    }
});
//Adds selected class to NEW button
$('.new').click(function() {
	$('.revertnew') .addClass("selected");
	$('.revertnew') .show();
	$('.new') .hide();
	$("#about").hide();
	$("#numbers").hide();
	$("#restaurantfilter").show();
	$('.showabout') .removeClass("selected");
	$('.bythenumbers') .removeClass("selected");
});
$('.revertnew').click(function() {
	$('.revertnew').hide();
	$('.new') .show();
	$("#about").hide();
	$("#numbers").hide();
	$("#restaurantfilter").show();
	$('.showabout') .removeClass("selected");
	$('.bythenumbers') .removeClass("selected");
});
//Display second search bar
$('#magnifying').click(function() {
 if ($(".clone") .is(':visible')) {
		$('.formclone') .hide();
		$('.clone') .hide();
    } else {
		$('.formclone') .css("display", "inline-block");
		$('.clone') .show();
		$('.showabout') .removeClass("selected");
		$('.bythenumbers') .removeClass("selected");
		$("#restaurantfilter").show();
		$("#about").hide();
		$("#numbers").hide();
	}
});
//JSON data
var app = angular.module('myApp', []);
     app.controller("MyCtrl", function($scope) {
	 $scope.filters = { };
	 $scope.restaurants = [
  {
    "rank": 1,
	"rankend":".",
    "name": "Xochi",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/1-Xochi-12171704.php",
    "image": "http://ww2.hdnux.com/photos/65/45/01/14045293/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "xochihouston.com",
    "links": "https://www.xochihouston.com/",
    "phone": "713-400-3330",
    "neighborhood": "Downtown",
    "nlink": "Downtown",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": 2,
	"rankend":".",
    "name": "BCN Taste & Tradition",
    "lastrank": 4,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/alison-cook/article/2-BCN-Taste-Tradition-12171748.php",
    "image": "http://ww1.hdnux.com/photos/51/52/13/10920696/3/rawImage.jpg",
    "cuisine": "Spanish",
    "clink": "Spanish",
    "website": "bcnhouston.com/",
    "links": "http://bcnhouston.com/",
    "phone": "832-834-3411",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": 3,
	"rankend":".",
    "name": "Coltivare",
    "lastrank": 11,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/3-Coltivare-12171771.php",
    "image": "http://ww2.hdnux.com/photos/61/17/45/12908901/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "agricolehospitality.com/coltivare",
    "links": "https://www.agricolehospitality.com/coltivare",
    "phone": "713-637-4095",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 4,
	"rankend":".",
    "name": "The Pass & Provisions",
    "lastrank": 3,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/4-The-Pass-Provisions-12171785.php",
    "image": "http://ww1.hdnux.com/photos/65/45/04/14045468/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "passandprovisions.com",
    "links": "http://www.passandprovisions.com",
    "phone": "713-628-9020",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "highpriced (The Pass) inexpensive to pricey to highpriced(Provisions)",
    "": ""
  },
  {
    "rank": 5,
	"rankend":".",
    "name": "Kata Robata",
    "lastrank": 13,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/5-Kata-Robata-12171812.php",
    "image": "http://ww2.hdnux.com/photos/65/45/05/14045525/3/rawImage.jpg",
    "cuisine": "Japanese",
    "clink": "Japanese",
    "website": "katarobata.com",
    "links": "https://www.katarobata.com/",
    "phone": "713-526-8858",
    "neighborhood": "Upper Kirby",
    "nlink": "kirby",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 6,
	"rankend":".",
    "name": "Hugo’s",
    "lastrank": 2,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/6-Hugo-s-12171835.php",
    "image": "http://ww1.hdnux.com/photos/65/45/06/14045596/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "hugosrestaurant.net",
    "links": "http://www.hugosrestaurant.net/",
    "phone": "713-524-7744",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 7,
	"rankend":".",
    "name": "Pondicheri",
    "lastrank": 7,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/7-Pondicheri-12171928.php",
    "image": "http://ww1.hdnux.com/photos/65/45/12/14045840/3/rawImage.jpg",
    "cuisine": "Indian",
    "clink": "Indian",
    "website": "pondichericafe.com",
    "links": "http://www.pondichericafe.com/",
    "phone": "713-522-2022",
    "neighborhood": "Upper Kirby",
    "nlink": "kirby",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": 8,
	"rankend":".",
    "name": "Killen’s Barbecue",
    "lastrank": 5,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/8-Killen-s-Barbecue-12171948.php",
    "image": "http://ww4.hdnux.com/photos/61/25/37/12933067/3/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "killensbarbecue.com",
    "links": "https://www.killensbarbecue.com/",
    "phone": "281-485-2272",
    "neighborhood": "Pearland",
    "nlink": "Pearland",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 9,
	"rankend":".",
    "name": "Helen Greek Food & Wine",
    "lastrank": 15,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/9-Helen-Greek-Food-Wine-12171970.php",
    "image": "http://ww2.hdnux.com/photos/65/45/14/14045969/3/rawImage.jpg",
    "cuisine": "Greek",
    "clink": "Greek",
    "website": "helengreek.com",
    "links": "http://www.helengreek.com/",
    "phone": "832-831-7133",
    "neighborhood": "Rice Village",
    "nlink": "rice",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 10,
	"rankend":".",
    "name": "Pax Americana",
    "lastrank": 6,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/10-Pax-Americana-12171993.php",
    "image": "http://ww3.hdnux.com/photos/65/45/15/14046062/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "paxamericanahtx.com",
    "links": "http://www.paxamericanahtx.com",
    "phone": "713-239-0228",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 11,
	"rankend":".",
    "name": "Maba Pan-Asian Diner",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/11-Maba-Pan-Asian-Diner-12172030.php",
    "image": "http://ww2.hdnux.com/photos/64/12/53/13675213/6/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "mabahouston.com",
    "links": "https://www.mabahouston.com/",
    "phone": "832-834-6157",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": 12,
	"rankend":".",
    "name": "Mala Sichuan Bistro",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/12-Mala-Sichuan-Bistro-12172055.php",
    "image": "http://ww1.hdnux.com/photos/65/45/23/14046408/3/rawImage.jpg",
    "cuisine": "Chinese",
    "clink": "Chinese",
    "website": "N/A",
    "links": "N/A",
    "phone": "713-995-1889",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": 13,
	"rankend":".",
    "name": "Himalaya",
    "lastrank": 10,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/13-Himalaya-12172061.php",
    "image": "http://ww1.hdnux.com/photos/65/45/23/14046444/3/rawImage.jpg",
    "cuisine": "Indian and Pakistani",
    "clink": "Indian and Pakistani",
    "website": "himalayarestauranthouston.com",
    "links": "http://www.himalayarestauranthouston.com",
    "phone": "713-532-2837",
    "neighborhood": "Sharpstown",
    "nlink": "Sharpstown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": 14,
	"rankend":".",
    "name": "Underbelly",
    "lastrank": 12,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/14-Underbelly-12172076.php",
    "image": "http://ww2.hdnux.com/photos/62/02/47/13117921/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "underbellyhouston.com",
    "links": "http://www.underbellyhouston.com/",
    "phone": "713-528-9800",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 15,
	"rankend":".",
    "name": "Killen’s STQ",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/15-Killen-s-STQ-12172089.php",
    "image": "http://ww3.hdnux.com/photos/65/45/24/14046494/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "killensstq.com",
    "links": "https://www.killensstq.com/",
    "phone": "713-586-0223",
    "neighborhood": "Briargrove",
    "nlink": "Briargrove",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 16,
	"rankend":".",
    "name": "Kitchen 713",
    "lastrank": "29 (2015)",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/16-Kitchen-713-12172167.php",
    "image": "http://ww4.hdnux.com/photos/65/45/27/14046663/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "kitchen713.com",
    "links": "http://www.kitchen713.com/",
    "phone": "713-842-7114",
    "neighborhood": "Washington Corridor",
    "nlink": "washington",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 17,
	"rankend":".",
    "name": "Rainbow Lodge",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/17-Rainbow-Lodge-12172177.php",
    "image": "http://ww3.hdnux.com/photos/65/45/27/14046674/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "rainbow-lodge.com",
    "links": "http://www.rainbow-lodge.com/",
    "phone": "713-861-8666",
    "neighborhood": "Heights/Shady Acres",
    "nlink": "Heights/Shady",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 18,
	"rankend":".",
    "name": "La Table",
    "lastrank": 21,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/18-La-Table-12172198.php",
    "image": "http://ww1.hdnux.com/photos/65/45/27/14046716/3/rawImage.jpg",
    "cuisine": "French",
    "clink": "French",
    "website": "latablehouston.com",
    "links": "https://latablehouston.com/",
    "phone": "713-439-1000",
    "neighborhood": "Uptown/Galleria",
    "nlink": "Uptown/Galleria",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": 19,
	"rankend":".",
    "name": "MF Sushi",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/19-MF-Sushi-12172202.php",
    "image": "http://ww2.hdnux.com/photos/65/45/30/14046729/3/rawImage.jpg",
    "cuisine": "Japanese",
    "clink": "Japanese",
    "website": "mfsushiusa.com",
    "links": "http://mfsushiusa.com/",
    "phone": "713-637-4587",
    "neighborhood": "Museum District",
    "nlink": "museum",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 20,
	"rankend":".",
    "name": "Saltillo Mexican Kitchen",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/20-Saltillo-Mexican-Kitchen-12172336.php",
    "image": "http://ww2.hdnux.com/photos/65/45/31/14046809/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "saltillomexicankitchen.com",
    "links": "http://www.saltillomexicankitchen.com/",
    "phone": "832-623-6467",
    "neighborhood": "Bellaire",
    "nlink": "Bellaire",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": 21,
	"rankend":".",
    "name": "Uchi",
    "lastrank": 22,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/21-Uchi-12172361.php",
    "image": "http://ww1.hdnux.com/photos/65/45/77/14049248/3/rawImage.jpg",
    "cuisine": "Japanese",
    "clink": "Japanese",
    "website": "uchirestaurants.com/houston",
    "links": "http://www.uchirestaurants.com/houston",
    "phone": "713-522-4808",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": 22,
	"rankend":".",
    "name": "Tony’s",
    "lastrank": 14,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/22-Tony-s-12173472.php",
    "image": "http://ww4.hdnux.com/photos/65/46/01/14049347/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "tonyshouston.com",
    "links": "http://www.tonyshouston.com",
    "phone": "713-622-6778",
    "neighborhood": "Greenway Plaza",
    "nlink": "greenway",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": 23,
	"rankend":".",
    "name": "Brasserie 1895",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/23-Brasserie-1895-12173499.php",
    "image": "http://ww4.hdnux.com/photos/65/46/10/14049843/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "brasserie1895.com",
    "links": "http://www.brasserie1895.com",
    "phone": "832-385-2278",
    "neighborhood": "Friendswood",
    "nlink": "Friendswood",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": 24,
	"rankend":".",
    "name": "Da Marco",
    "lastrank": 17,
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/24-Da-Marco-12173541.php",
    "image": "http://ww2.hdnux.com/photos/65/46/00/14049285/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "damarcohouston.com",
    "links": "http://www.damarcohouston.com/",
    "phone": "713-807-8857",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": 25,
	"rankend":".",
    "name": "Riel",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/25-Riel-12173569.php",
    "image": "http://ww2.hdnux.com/photos/64/12/53/13675249/6/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "rielhtx.com",
    "links": "https://www.rielhtx.com/",
    "phone": "832-831-9109",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "pricey",
    "": ""
  },
  {
    "rank": 26,
	"rankend":".",
    "name": "Giacomo’s Cibo e Vino",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/26-Giacomo-s-Cibo-e-Vino-12173593.php",
    "image": "http://ww3.hdnux.com/photos/65/46/10/14049854/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "giacomosciboevino.com",
    "links": "http://www.giacomosciboevino.com/",
    "phone": "713-522-1934",
    "neighborhood": "River Oaks",
    "nlink": "riveroaks",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": 27,
	"rankend":".",
    "name": "Killen’s Steakhouse",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/27-Killen-s-Steakhouse-12173603.php",
    "image": "http://ww1.hdnux.com/photos/60/67/37/12810232/3/rawImage.jpg",
    "cuisine": "Steakhouse",
    "clink": "Steakhouse",
    "website": "killenssteakhouse.com",
    "links": "https://www.killenssteakhouse.com/",
    "phone": "281-485-0844",
    "neighborhood": "Pearland",
    "nlink": "Pearland",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": 28,
	"rankend":".",
    "name": "Good Dog Houston",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/28-Good-Dog-Houston-12173614.php",
    "image": "http://ww3.hdnux.com/photos/65/46/05/14049602/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "gooddoghouston.com",
    "links": "http://gooddoghouston.com/",
    "phone": "832-800-3647",
    "neighborhood": "Heights, Montrose",
    "nlink": "Heights, Montrose",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": 29,
	"rankend":".",
    "name": "Roost",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/29-Roost-12173664.php",
    "image": "http://ww1.hdnux.com/photos/65/46/05/14049624/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "iloveroost.com",
    "links": "http://www.iloveroost.com",
    "phone": "713-523-7667",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": 30,
	"rankend":".",
    "name": "Andes Cafe",
    "lastrank": "26-100",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/30-Andes-Cafe-12173727.php",
    "image": "http://ww2.hdnux.com/photos/62/65/51/13326929/3/rawImage.jpg",
    "cuisine": "South American",
    "clink": "SouthAm",
    "website": "andescafe.com",
    "links": "http://www.andescafe.com/",
    "phone": "832-659-0063",
    "neighborhood": "East End",
    "nlink": "eastend",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Afandim Restaurant",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Afandim-Restaurant-12174200.php",
    "image": "http://ww3.hdnux.com/photos/65/46/11/14049918/3/rawImage.jpg",
    "cuisine": "Chinese",
    "clink": "Chinese",
    "website": "N/A",
    "links": "N/A",
    "phone": "281-888-5597",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Aim Thai",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Aim-Thai-12174233.php",
    "image": "http://ww4.hdnux.com/photos/60/61/22/12784771/3/rawImage.jpg",
    "cuisine": "Thai",
    "clink": "Thai",
    "website": "aimthai.weebly.com",
    "links": "http://www.aimthai.weebly.com",
    "phone": "832-230-3330",
    "neighborhood": "Acres Homes",
    "nlink": "acres",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Banana Leaf Malaysian Cuisine",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Banana-Leaf-Malaysian-Cuisine-12174265.php",
    "image": "http://ww1.hdnux.com/photos/60/67/35/12810048/3/rawImage.jpg",
    "cuisine": "Malaysian",
    "clink": "Malaysian",
    "website": "N/A",
    "links": "N/A",
    "phone": "713-771-8118",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Bernie’s Burger Bus",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Bernie-s-Burger-Bus-12174280.php",
    "image": "http://ww1.hdnux.com/photos/56/64/20/12272676/3/rawImage.jpg",
    "cuisine": "Burgers/sandwiches",
    "clink": "Burgers/sandwiches",
    "website": "berniesburgerbus.com",
    "links": "http://www.berniesburgerbus.com/",
    "phone": "Multiple locations",
    "neighborhood": "Katy, Bellaire, Heights",
    "nlink": "Katy, Bellaire, Heights",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Bon Ga Garden Korean Restaurant",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Bon-Ga-Garden-Korean-Restaurant-12174325.php",
    "image": "http://ww2.hdnux.com/photos/45/65/21/9917549/3/rawImage.jpg",
    "cuisine": "Korean",
    "clink": "Korean",
    "website": "N/A",
    "links": "N/A",
    "phone": "713-461-5265",
    "neighborhood": "Spring Branch",
    "nlink": "spbranch",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "The Breakfast Klub",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/The-Breakfast-Klub-12174344.php",
    "image": "http://ww3.hdnux.com/photos/60/67/43/12810442/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "thebreakfastklub.com",
    "links": "https://thebreakfastklub.com/",
    "phone": "713-528-8561",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Burger Chan",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Burger-Chan-12174354.php",
    "image": "http://ww1.hdnux.com/photos/64/12/53/13675200/6/rawImage.jpg",
    "cuisine": "Burgers/sandwiches",
    "clink": "Burgers/sandwiches",
    "website": "burgerchanhtx.com",
    "links": "https://burgerchanhtx.com/",
    "phone": "832-542-3528",
    "neighborhood": "Greenway Plaza",
    "nlink": "greenway",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Cafe TH",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Cafe-TH-12174526.php",
    "image": "http://ww3.hdnux.com/photos/65/46/14/14050050/3/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "cafeth.com",
    "links": "http://www.cafeth.com",
    "phone": "713-225-4766",
    "neighborhood": "East Downtown",
    "nlink": "eastdo",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Cajun Kitchen",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Cajun-Kitchen-12174567.php",
    "image": "http://ww4.hdnux.com/photos/64/12/52/13675199/6/rawImage.jpg",
    "cuisine": "Vietnamese, Creole/Cajun",
    "clink": "Vietnamese, Creole/Cajun",
    "website": "cajunkitchenhouston.com",
    "links": "http://cajunkitchenhouston.com/",
    "phone": "281-495-8881",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Caracol",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Caracol-12174582.php",
    "image": "http://ww3.hdnux.com/photos/51/43/11/10891890/3/rawImage.jpg",
    "cuisine": "Seafood, Mexican",
    "clink": "Seafood, Mexican",
    "website": "caracol.net",
    "links": "http://www.caracol.net/",
    "phone": "713-622-9996",
    "neighborhood": "Uptown/Galleria",
    "nlink": "Uptown/Galleria",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Cedar’s Bakery",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Cedar-s-Bakery-12174608.php",
    "image": "http://ww4.hdnux.com/photos/25/76/05/5759319/6/rawImage.jpg",
    "cuisine": "Mediterranean",
    "clink": "Mediterranean",
    "website": "facebook.com/Cedars-Bakery",
    "links": "https://www.facebook.com/Cedars-Bakery-126030392023/",
    "phone": "713-706-4141",
    "neighborhood": "Woodlake/Briar Meadow",
    "nlink": "Woodlake/BriarMeadow",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "CorkScrew BBQ",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/CorkScrew-BBQ-12174626.php",
    "image": "http://ww4.hdnux.com/photos/61/31/66/12950967/3/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "corkscrewbbq.com",
    "links": "https://www.corkscrewbbq.com/",
    "phone": "832-592-1184",
    "neighborhood": "Spring",
    "nlink": "Spring",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Costa Brava Bistro",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Costa-Brava-Bistro-12174636.php",
    "image": "http://ww2.hdnux.com/photos/17/20/74/4001573/3/rawImage.jpg",
    "cuisine": "Spanish",
    "clink": "Spanish",
    "website": "costabravabistro.com",
    "links": "http://www.costabravabistro.com/",
    "phone": "713-839-1005",
    "neighborhood": "Bellaire",
    "nlink": "Bellaire",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Crawfish & Noodles",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Crawfish-Noodles-12174660.php",
    "image": "http://ww1.hdnux.com/photos/60/01/77/12591060/6/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "facebook.com/crawfishandnoodles",
    "links": "https://www.facebook.com/crawfishandnoodles",
    "phone": "281-988-8098",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Cuchara",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Cuchara-12174706.php",
    "image": "http://ww4.hdnux.com/photos/56/45/67/12213707/5/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "cuchararestaurant.com",
    "links": "http://www.cuchararestaurant.com/",
    "phone": "713-942-0000",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Dolce Vita",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Dolce-Vita-12174718.php",
    "image": "http://ww4.hdnux.com/photos/32/26/71/6909519/10/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "dolcevitahouston.com",
    "links": "http://www.dolcevitahouston.com/",
    "phone": "713-520-8222",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Etoile Cuisine et Bar",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Etoile-Cuisine-et-Bar-12175262.php",
    "image": "http://ww1.hdnux.com/photos/51/43/06/10891688/3/rawImage.jpg",
    "cuisine": "French",
    "clink": "French",
    "website": "etoilecuisine.com",
    "links": "http://www.etoilecuisine.com/",
    "phone": "832-668-5808",
    "neighborhood": "Uptown/Galleria",
    "nlink": "Uptown/Galleria",
    "price": "pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Fielding’s Local Kitchen + Bar",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Fielding-s-Local-Kitchen-Bar-12177017.php",
    "image": "http://ww3.hdnux.com/photos/51/56/22/10937526/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "fieldingslocal.com",
    "links": "https://fieldingslocal.com/",
    "phone": "281-351-2225",
    "neighborhood": "The Woodlands",
    "nlink": "woodlands",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Frenchy’s Chicken",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Frenchy-s-Chicken-12177044.php",
    "image": "http://ww3.hdnux.com/photos/65/46/21/14050422/3/rawImage.jpg",
    "cuisine": "Creole/Cajun",
    "clink": "Creole/Cajun",
    "website": "frenchyschicken.com",
    "links": "http://www.frenchyschicken.com/",
    "phone": "713-748-2233",
    "neighborhood": "Third Ward",
    "nlink": "thirdward",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Gatlin’s BBQ",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Gatlin-s-BBQ-12177058.php",
    "image": "http://ww1.hdnux.com/photos/64/01/30/13637152/5/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "gatlinsbbq.com",
    "links": "http://www.gatlinsbbq.com/",
    "phone": "713-869-4227",
    "neighborhood": "Oak Forest",
    "nlink": "oakforest",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Great W’Kana Café",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Great-W-Kana-Cafe-12177099.php",
    "image": "http://ww2.hdnux.com/photos/32/26/71/6909529/7/rawImage.jpg",
    "cuisine": "Indian",
    "clink": "Indian",
    "website": "www.greatwkanacafe.com",
    "links": "http://www.greatwkanacafe.com/",
    "phone": "832-886-4291",
    "neighborhood": "Eldridge",
    "nlink": "Eldridge",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Gusto Gourmet",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Gusto-Gourmet-12177119.php",
    "image": "http://ww2.hdnux.com/photos/64/37/00/13758513/3/rawImage.jpg",
    "cuisine": "Venezuelan/Middle Eastern",
    "clink": "Venezuelan/Mideast",
    "website": "gustogourmettogo.com",
    "links": "http://www.gustogourmettogo.com",
    "phone": "713-344-0892",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Habanera & the Guero",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Habanera-and-the-Guero-12177130.php",
    "image": "http://ww3.hdnux.com/photos/41/61/67/8854990/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "facebook.com/HabaneraAndTheG",
    "links": "https://www.facebook.com/HabaneraAndTheG",
    "phone": "832-547-1240",
    "neighborhood": "Hobby area",
    "nlink": "hobby",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Hai Cang Seafood Restaurant",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Hai-Cang-Seafood-Restaurant-12177147.php",
    "image": "http://ww2.hdnux.com/photos/36/47/05/8024413/3/rawImage.jpg",
    "cuisine": "Chinese, Seafood",
    "clink": "Chinese, Seafood",
    "website": "haicangrestaurant.net",
    "links": "http://www.haicangrestaurant.net/",
    "phone": "281-564-4288",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "cheap to inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Harold’s",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Harold-s-12177158.php",
    "image": "http://ww1.hdnux.com/photos/64/12/53/13675208/6/rawImage.jpg",
    "cuisine": "Contemporary American, Creole/Cajun",
    "clink": "ContempAm, Creole/Cajun",
    "website": "haroldsheights.com",
    "links": "http://www.haroldsheights.com/",
    "phone": "713-360-6204",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Holley’s Seafood Restaurant & Oyster Bar",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Holley-s-Seafood-Restaurant-Oyster-Bar-12177171.php",
    "image": "http://ww3.hdnux.com/photos/60/74/50/12831250/3/rawImage.jpg",
    "cuisine": "Seafood",
    "clink": "Seafood",
    "website": "holleyshouston.com",
    "links": "http://www.holleyshouston.com",
    "phone": "713-491-2222",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Hubbell & Hudson Bistro/Cureight",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Hubbell-Hudson-Bistro-Cureight-12177207.php",
    "image": "http://ww1.hdnux.com/photos/40/73/25/8631656/5/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "hubbellandhudson.com/cureight",
    "links": "http://www.hubbellandhudson.com/cureight/",
    "phone": "281-203-5641",
    "neighborhood": "The Woodlands",
    "nlink": "woodlands",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Hubcap Grill",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Hubcap-Grill-12177315.php",
    "image": "http://ww2.hdnux.com/photos/46/26/77/10055653/5/rawImage.jpg",
    "cuisine": "Burgers/sandwiches",
    "clink": "Burgers/sandwiches",
    "website": "hubcapgrill.com",
    "links": "http://www.hubcapgrill.com",
    "phone": "Multiple locations",
    "neighborhood": "Downtown, Heights, Kemah",
    "nlink": "Downtown, Heights, Kemah",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Huynh Restaurant",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Huynh-Restaurant-12177331.php",
    "image": "http://ww4.hdnux.com/photos/45/65/21/9917551/3/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "huynhrestauranthouston.com",
    "links": "http://www.huynhrestauranthouston.com",
    "phone": "713-224-8964",
    "neighborhood": "East Downtown",
    "nlink": "eastdo",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Irma’s Original",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Irma-s-Original-12177358.php",
    "image": "http://ww2.hdnux.com/photos/56/45/67/12213717/5/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "irmasoriginal.com",
    "links": "https://irmasoriginal.com/",
    "phone": "713-222-0767",
    "neighborhood": "Downtown",
    "nlink": "Downtown",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Izakaya",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Izakaya-12177377.php",
    "image": "http://ww2.hdnux.com/photos/64/12/53/13675209/6/rawImage.jpg",
    "cuisine": "Japanese",
    "clink": "Japanese",
    "website": "houstonizakaya.com",
    "links": "http://www.houstonizakaya.com",
    "phone": "713-527-8988",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Kiran’s",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Kiran-s-12177395.php",
    "image": "http://ww4.hdnux.com/photos/57/13/03/12366019/3/rawImage.jpg",
    "cuisine": "Indian",
    "clink": "Indian",
    "website": "kiranshouston.com",
    "links": "http://www.kiranshouston.com",
    "phone": "713-960-8472",
    "neighborhood": "Upper Kirby",
    "nlink": "kirby",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Kuu",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Kuu-12177417.php",
    "image": "http://ww3.hdnux.com/photos/60/67/35/12810058/3/rawImage.jpg",
    "cuisine": "Japanese",
    "clink": "Japanese",
    "website": "kuurestaurant.com",
    "links": "http://www.kuurestaurant.com/",
    "phone": "713-461-1688",
    "neighborhood": "Memorial City",
    "nlink": "memcity",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Latin Bites",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Latin-Bites-12177555.php",
    "image": "http://ww2.hdnux.com/photos/51/52/04/10920209/3/rawImage.jpg",
    "cuisine": "South American",
    "clink": "SouthAm",
    "website": "latinbitescafe.com",
    "links": "https://www.latinbitescafe.com/",
    "phone": "713-229-8369",
    "neighborhood": "Tanglewood",
    "nlink": "Tanglewood",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Local Foods",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Local-Foods-12177565.php",
    "image": "http://ww3.hdnux.com/photos/56/66/21/12280930/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "houstonlocalfoods.com",
    "links": "http://www.houstonlocalfoods.com/",
    "phone": "Multiple locations",
    "neighborhood": "Downtown, Rice Village, Upper Kirby, Tanglewood",
    "nlink": "Downtown, rice, kirby, Tanglewood",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Lupita’s Mexican Restaurant",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Lupita-s-Mexican-Restaurant-12177580.php",
    "image": "http://ww2.hdnux.com/photos/36/53/53/8043209/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "lupitassugarland.com",
    "links": "http://www.lupitassugarland.com/",
    "phone": "281-265-6556",
    "neighborhood": "Sugar Land",
    "nlink": "sugarland",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Mein",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Mein-12177591.php",
    "image": "http://ww2.hdnux.com/photos/56/31/25/12162373/3/rawImage.jpg",
    "cuisine": "Chinese",
    "clink": "Chinese",
    "website": "eatmein.com",
    "links": "http://www.eatmein.com/",
    "phone": "713-923-7488",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Melange Creperie",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Melange-Creperie-12177603.php",
    "image": "http://ww1.hdnux.com/photos/46/30/30/10061340/3/rawImage.jpg",
    "cuisine": "French",
    "clink": "French",
    "website": "houstoncrepes.com",
    "links": "http://www.houstoncrepes.com/",
    "phone": "832-724-9464",
    "neighborhood": "Downtown",
    "nlink": "Downtown",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Mezzanotte",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Mezzanotte-12177612.php",
    "image": "http://ww4.hdnux.com/photos/23/50/73/5148371/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "mezzanotte.tv",
    "links": "http://www.mezzanotte.tv/",
    "phone": "832-717-7870",
    "neighborhood": "Cypress",
    "nlink": "Cypress",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Morningstar",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Morningstar-12177627.php",
    "image": "http://ww4.hdnux.com/photos/64/12/53/13675243/6/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "facebook.com/MorningstarHOU",
    "links": "https://www.facebook.com/MorningstarHOU",
    "phone": "832-806-1115",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Nam Giao",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Nam-Giao-12177633.php",
    "image": "http://ww4.hdnux.com/photos/44/63/23/9647351/3/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "N/A",
    "links": "N/A",
    "phone": "281-568-4888",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Nobie’s",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Nobie-s-12177647.php",
    "image": "http://ww2.hdnux.com/photos/64/12/53/13675245/6/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "nobieshtx.com",
    "links": "http://www.nobieshtx.com/",
    "phone": "346-319-5919",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Oporto Fooding House & Wine",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Oporto-Fooding-House-Wine-12177663.php",
    "image": "http://ww4.hdnux.com/photos/40/02/32/8398511/3/rawImage.jpg",
    "cuisine": "Portuguese",
    "clink": "Portuguese",
    "website": "oportomidtown.us",
    "links": "https://www.oportomidtown.us/",
    "phone": "713-528-0115",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "The Original Kolache Shoppe",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/The-Original-Kolache-Shoppe-12177677.php",
    "image": "http://ww2.hdnux.com/photos/60/34/60/12700733/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "originalkolache.com",
    "links": "http://www.originalkolache.com/",
    "phone": "713-649-0711",
    "neighborhood": "Gulfgate",
    "nlink": "Gulfgate",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "The Original Ninfa’s on Navigation",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/The-Original-Ninfa-s-on-Navigation-12177686.php",
    "image": "http://ww4.hdnux.com/photos/56/45/67/12213723/5/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "ninfas.com",
    "links": "http://www.ninfas.com",
    "phone": "713-228-1175",
    "neighborhood": "East End",
    "nlink": "eastend",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Pappas Bros. Steakhouse",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pappas-Bros-Steakhouse-12177741.php",
    "image": "http://ww3.hdnux.com/photos/56/45/67/12213698/3/rawImage.jpg",
    "cuisine": "Steakhouse",
    "clink": "Steakhouse",
    "website": "pappasbros.com",
    "links": "http://www.pappasbros.com/home/",
    "phone": "Multiple locations",
    "neighborhood": "Downtown, Galleria",
    "nlink": "Downtown, Galleria",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Pepper Twins",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pepper-Twins-12177761.php",
    "image": "http://ww4.hdnux.com/photos/56/02/63/12070115/3/rawImage.jpg",
    "cuisine": "Chinese",
    "clink": "Chinese",
    "website": "txpeppertwins.com",
    "links": "http://www.txpeppertwins.com/",
    "phone": "Multiple locations",
    "neighborhood": "Montrose, River Oaks, Upper Kirby",
    "nlink": "Montrose, riveroaks, kirby",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Pi Pizza",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pi-Pizza-12177769.php",
    "image": "http://ww3.hdnux.com/photos/54/24/62/11619494/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "pipizzahtx.com",
    "links": "http://www.pipizzahtx.com/",
    "phone": "832-767-2433",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Pho Binh Trailer/Pho Binh by Night",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pho-Binh-Trailer-Pho-Binh-By-Night-12177781.php",
    "image": "http://ww4.hdnux.com/photos/23/50/70/5148171/5/rawImage.jpg",
    "cuisine": "Vietnamese",
    "clink": "Vietnamese",
    "website": "phobinh.com",
    "links": "http://www.phobinh.com/",
    "phone": "281-484-3963",
    "neighborhood": "Southbelt/Ellington, Chinatown",
    "nlink": "Southbelt/Ellington, Chinatown",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Picos",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Picos-12177789.php",
    "image": "http://ww1.hdnux.com/photos/46/26/75/10055548/7/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "picos.net",
    "links": "https://www.picos.net/",
    "phone": "832-831-9940",
    "neighborhood": "Upper Kirby",
    "nlink": "kirby",
    "price": "inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Pierogi Queen",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pierogi-Queen-12177816.php",
    "image": "http://ww4.hdnux.com/photos/56/31/43/12163307/3/rawImage.jpg",
    "cuisine": "Polish",
    "clink": "Polish",
    "website": "pierogiqueentx.com",
    "links": "http://www.pierogiqueentx.com/",
    "phone": "713-244-4644",
    "neighborhood": "League City",
    "nlink": "leaguecity",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Pinkerton’s Barbecue",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pinkerton-s-Barbecue-12177849.php",
    "image": "http://ww2.hdnux.com/photos/55/66/32/12019377/7/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "pinkertonsbarbecue.com",
    "links": "http://www.pinkertonsbarbecue.com/",
    "phone": "713-802-2000",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Pizaro’s Pizza Napoletana",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Pizaro-s-Pizza-Napoletana-12177854.php",
    "image": "http://ww1.hdnux.com/photos/32/06/45/6842744/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "pizarospizza.com",
    "links": "http://www.pizarospizza.com",
    "phone": "Multiple locations",
    "neighborhood": "Memorial, Montrose",
    "nlink": "Memorial, Montrose",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Reef",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Reef-12177867.php",
    "image": "http://ww4.hdnux.com/photos/56/45/70/12213815/5/rawImage.jpg",
    "cuisine": "Seafood",
    "clink": "Seafood",
    "website": "reefhouston.com",
    "links": "http://www.reefhouston.com/",
    "phone": "713-526-8282",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Revival Market",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Revival-Market-12177875.php",
    "image": "http://ww2.hdnux.com/photos/54/60/73/11734757/7/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "revivalmarket.com",
    "links": "https://www.agricolehospitality.com/revival-market/",
    "phone": "713-880-8463",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Rice Bowl Indonesian",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Rice-Bowl-Indonesian-12177911.php",
    "image": "http://ww1.hdnux.com/photos/23/56/16/5170056/55/rawImage.jpg",
    "cuisine": "Indonesian/Chinese",
    "clink": "Indonesian/Chinese",
    "website": "ricebowlhouston.com",
    "links": "http://www.ricebowlhouston.com/",
    "phone": "281-988-9912",
    "neighborhood": "Chinatown",
    "nlink": "Chinatown",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Ritual",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Ritual-12177928.php",
    "image": "http://ww3.hdnux.com/photos/64/12/53/13675250/6/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "ritualhouston.com",
    "links": "http://www.ritualhouston.com/",
    "phone": "832-203-5180",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Roegels Barbecue Co.",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Roegels-Barbecue-Co-12177948.php",
    "image": "http://ww1.hdnux.com/photos/61/31/67/12950976/3/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "roegelsbarbecue.com",
    "links": "http://www.roegelsbarbecue.com/",
    "phone": "713-977-8725",
    "neighborhood": "Briargrove",
    "nlink": "Briargrove",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "SaltAir Seafood Kitchen",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/SaltAir-Seafood-Kitchen-12177962.php",
    "image": "http://ww1.hdnux.com/photos/60/74/50/12831248/3/rawImage.jpg",
    "cuisine": "Seafood",
    "clink": "Seafood",
    "website": "saltairhouston.com",
    "links": "https://www.saltairhouston.com/",
    "phone": "713-521-3333",
    "neighborhood": "Upper Kirby",
    "nlink": "kirby",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Shri Balaji Bhavan",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Shri-Balaji-Bhavan-12177973.php",
    "image": "http://ww1.hdnux.com/photos/51/52/03/10920172/3/rawImage.jpg",
    "cuisine": "Indian",
    "clink": "Indian",
    "website": "N/A",
    "links": "N/A",
    "phone": "713-783-1126",
    "neighborhood": "Sharpstown",
    "nlink": "Sharpstown",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Southern Goods",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Southern-Goods-12177993.php",
    "image": "http://ww1.hdnux.com/photos/62/02/53/13118204/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "southerngoodshouston.com",
    "links": "https://southerngoodshouston.com/",
    "phone": "346-980-8152",
    "neighborhood": "Heights",
    "nlink": "Heights",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "State Fare",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/State-Fare-12178005.php",
    "image": "http://ww2.hdnux.com/photos/57/13/70/12369449/3/rawImage.jpg",
    "cuisine": "American",
    "clink": "American",
    "website": "statefaretx.com",
    "links": "http://www.statefaretx.com",
    "phone": "832-831-0950",
    "neighborhood": "Memorial City",
    "nlink": "memcity",
    "price": "pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "State of Grace",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/State-of-Grace-12178024.php",
    "image": "http://ww4.hdnux.com/photos/61/77/17/13104083/3/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "stateofgracetx.com",
    "links": "http://www.stateofgracetx.com",
    "phone": "832-942-5080",
    "neighborhood": "River Oaks",
    "nlink": "riveroaks",
    "price": "inexpensive to pricey to highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Sylvia’s Enchilada Kitchen",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Sylvia-s-Enchilada-Kitchen-12178037.php",
    "image": "http://ww4.hdnux.com/photos/37/10/21/8160335/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "sylviasenchiladas.com",
    "links": "http://www.sylviasenchiladas.com/",
    "phone": "Multiple locations",
    "neighborhood": "Eldridge, Tanglewood",
    "nlink": "Eldridge, Tanglewood",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Tejas Chocolate Craftory",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Tejas-Chocolate-Craftory-12178050.php",
    "image": "http://ww2.hdnux.com/photos/62/02/52/13118113/3/rawImage.jpg",
    "cuisine": "Barbecue",
    "clink": "Barbecue",
    "website": "tejaschocolate.com",
    "links": "http://www.tejaschocolate.com",
    "phone": "832-761-0670",
    "neighborhood": "Tomball",
    "nlink": "Tomball",
    "price": "inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Vic & Anthony’s",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Vic-Anthony-s-12178076.php",
    "image": "http://ww3.hdnux.com/photos/56/45/67/12213702/5/rawImage.jpg",
    "cuisine": "Steakhouse",
    "clink": "Steakhouse",
    "website": "vicandanthonys.com",
    "links": "http://www.vicandanthonys.com/",
    "phone": "713-228-1111",
    "neighborhood": "Downtown",
    "nlink": "Downtown",
    "price": "highpriced",
    "": ""
  },
  {
    "rank": "",
    "name": "Villa Arcos",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Villa-Arcos-12178094.php",
    "image": "http://ww2.hdnux.com/photos/42/60/41/9111617/3/rawImage.jpg",
    "cuisine": "Mexican/Tex-Mex",
    "clink": "Mexican/Tex-Mex",
    "website": "originalvillaarcos.com",
    "links": "https://www.originalvillaarcos.com/",
    "phone": "713-826-1099",
    "neighborhood": "East End",
    "nlink": "eastend",
    "price": "cheap",
    "": ""
  },
  {
    "rank": "",
    "name": "Vinoteca Poscol",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Vinoteca-Poscol-12178110.php",
    "image": "http://ww3.hdnux.com/photos/37/70/14/8356630/3/rawImage.jpg",
    "cuisine": "Italian",
    "clink": "Italian",
    "website": "poscolhouston.com",
    "links": "http://www.poscolhouston.com",
    "phone": "713-529-2797",
    "neighborhood": "Montrose",
    "nlink": "Montrose",
    "price": "cheatp to inexpensive",
    "": ""
  },
  {
    "rank": "",
    "name": "Weights + Measures",
    "lastrank": "",
    "new": "",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Weights-Measures-12178121.php",
    "image": "http://ww4.hdnux.com/photos/44/14/04/9486595/5/rawImage.jpg",
    "cuisine": "Contemporary American",
    "clink": "ContempAm",
    "website": "weights-measures.com",
    "links": "http://www.weights-measures.com",
    "phone": "713-654-1970",
    "neighborhood": "Midtown",
    "nlink": "Midtown",
    "price": "cheap to inexpensive to pricey",
    "": ""
  },
  {
    "rank": "",
    "name": "Yauatcha",
    "lastrank": "",
    "new": "NEW",
    "story": "http://www.houstonchronicle.com/entertainment/top-100-restaurants/article/Yauatcha-12178130.php",
    "image": "http://ww3.hdnux.com/photos/61/06/50/12872198/3/rawImage.jpg",
    "cuisine": "Chinese",
    "clink": "Chinese",
    "website": "yauatcha.com",
    "links": "http://www.yauatcha.com/",
    "phone": "713-357-7588",
    "neighborhood": "Uptown/Galleria",
    "nlink": "Uptown/Galleria",
    "price": "pricey to highpriced",
    "": ""
  }
];
//Clear filter function
$scope.clearFilter = function() {
      $scope.filters = {}; 
	  $scope.filters2 = {};
		if ($scope.search !== undefined) {
            $scope.search = undefined;
        }
		if ($scope.search2 !== undefined) {
            $scope.search2 = undefined;
        }
    };
});